- name: Configure NTP server
  hosts: NTP
  become: yes

  vars:
    ntp_allowed_networks:
      - 10.20.0.0/16
    ntp_pools:
      - dk.pool.ntp.org

  tasks:
    - name: Ensure apt cache is updated
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install chrony
      apt:
        name: chrony
        state: present
        update_cache: yes
        force_apt_get: yes

    - name: Ensure chrony service is enabled and running
      systemd:
        name: chrony
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Remove old pool/server lines
      lineinfile:
        path: /etc/chrony/chrony.conf
        regexp: '^(pool|server) '
        state: absent

    - name: Add DK pool
      blockinfile:
        path: /etc/chrony/chrony.conf
        block: |
          {% for pool in ntp_pools %}
          pool {{ pool }} iburst
          {% endfor %}
        marker: "# {mark} ANSIBLE NTP POOLS"

    - name: Allow internal networks
      blockinfile:
        path: /etc/chrony/chrony.conf
        block: |
          {% for net in ntp_allowed_networks %}
          allow {{ net }}
          {% endfor %}
        marker: "# {mark} ANSIBLE ALLOW NETWORKS"

    - name: Restart chrony if config changed
      systemd:
        name: chrony
        state: restarted

    - name: Open NTP port in UFW
      ufw:
        rule: allow
        port: 123
        proto: udp
