---
- name: Setup phpIPAM server with Nginx
  hosts: phpIPAM
  become: true
  vars:
    phpipam_db_name: "phpipam"
    phpipam_db_user: "phpipamuser"
    phpipam_db_password: "Merc1234!"
    phpipam_version: "1.7.3"  # latest release
    phpipam_install_dir: "/var/www/phpipam"
    mysql_root_password: "Merc1234!"
    server_name: "ipam.be.local"
    php_timezone: "Europe/Copenhagen"

  tasks:

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - nginx
          - mariadb-server
          - php-fpm
          - php-mysql
          - php-gd
          - php-cli
          - php-curl
          - php-mbstring
          - php-xml
          - unzip
          - wget
        state: present

    - name: Start and enable Nginx and MariaDB
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - nginx
        - mariadb

    - name: Ensure MariaDB root password is set
      ansible.builtin.command: >
        mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}';"

    - name: Create phpIPAM database
      ansible.builtin.command: >
        mysql -uroot -p'{{ mysql_root_password }}' -e "CREATE DATABASE IF NOT EXISTS {{ phpipam_db_name }} CHARACTER SET utf8 COLLATE utf8_general_ci;"

    - name: Create phpIPAM database user
      ansible.builtin.command: >
        mysql -uroot -p'{{ mysql_root_password }}' -e "CREATE USER IF NOT EXISTS '{{ phpipam_db_user }}'@'localhost' IDENTIFIED BY '{{ phpipam_db_password }}'; GRANT ALL PRIVILEGES ON {{ phpipam_db_name }}.* TO '{{ phpipam_db_user }}'@'localhost'; FLUSH PRIVILEGES;"

    - name: Clone phpIPAM repository
      ansible.builtin.git:
        repo: 'https://github.com/phpipam/phpipam.git'
        dest: '{{ phpipam_install_dir }}'
        version: '1.7'  # specific release
        recursive: yes


    - name: Set ownership for Nginx
      ansible.builtin.file:
        path: "{{ phpipam_install_dir }}"
        owner: www-data
        group: www-data
        recurse: yes
        
    - name: Get installed PHP version
      ansible.builtin.command: php -r "echo PHP_VERSION;"
      register: php_version_raw

    - name: Set PHP major.minor version fact
      ansible.builtin.set_fact:
        php_version: "{{ php_version_raw.stdout | regex_search('^([0-9]+\\.[0-9]+)') }}"

    - name: Configure PHP timezone
      ansible.builtin.lineinfile:
        path: "/etc/php/{{ php_version }}/fpm/php.ini"
        regexp: '^;?date.timezone ='
        line: "date.timezone = {{ php_timezone }}"
        state: present
      notify: Restart PHP-FPM


    - name: Configure Nginx for phpIPAM
      ansible.builtin.copy:
        dest: /etc/nginx/sites-available/phpipam
        content: |
          server {
              listen 80;
              server_name {{ server_name }};
              
              root {{ phpipam_install_dir }};
              index index.php;

              location / {
                  try_files $uri $uri/ /index.php;
              }

              location ~ \.php$ {
                  include snippets/fastcgi-php.conf;
                  fastcgi_pass unix:/run/php/php{{ ansible_facts.packages.php[0].version | regex_search('^([0-9]+\\.[0-9]+)') }}-fpm.sock;
              }

              location ~ /\.ht {
                  deny all;
              }
          }

    - name: Enable phpIPAM site
      ansible.builtin.file:
        src: /etc/nginx/sites-available/phpipam
        dest: /etc/nginx/sites-enabled/phpipam
        state: link

    - name: Remove default Nginx site
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

    - name: Restart PHP-FPM
      ansible.builtin.service:
        name: "php{{ ansible_facts.packages.php[0].version | regex_search('^([0-9]+\\.[0-9]+)') }}-fpm"
        state: restarted
