- hosts: dns
  become: true
  vars:
    # --- Forward Zone Variables ---
    zone_name: be.local
    ttl: 86400
    serial: 2026012801

    ns_records:
      - ns1

    a_records:
      - name: ns1
        ip: 10.20.10.111
      - name: proxmox-node1
        ip: 10.20.10.11

    cname_records: []

    # --- Reverse Zone Variables ---
    reverse_zones:
      - zone_name: "10.20.10.in-addr.arpa"
        ttl: 86400
        serial: 2026012801
        ptr_records:
          - ip_last_octet: 111
            hostname: ns1.be.local.
          - ip_last_octet: 11
            hostname: proxmox-node1.be.local.
      - zone_name: "2.20.10.in-addr.arpa"
        ttl: 86400
        serial: 2026012801
        ptr_records: []
      - zone_name: "1.20.10.in-addr.arpa"
        ttl: 86400
        serial: 2026012801
        ptr_records: []
      - zone_name: "40.20.10.in-addr.arpa"
        ttl: 86400
        serial: 2026012801
        ptr_records: []
      - zone_name: "99.20.10.in-addr.arpa"
        ttl: 86400
        serial: 2026012801
        ptr_records: []

  tasks:
    - name: Install BIND9
      apt:
        name: bind9
        state: present
        update_cache: yes

    - name: Ensure BIND zones directory exists
      file:
        path: /etc/bind/zones
        state: directory
        owner: root
        group: bind
        mode: '0755'

    - name: Deploy named.conf.options
      template:
        src: templates/named.conf.options.j2
        dest: /etc/bind/named.conf.options
        owner: root
        group: bind
        mode: '0644'
      notify:
        - restart bind9


    # --- Forward Zone ---
    - name: Deploy forward DNS zone file
      template:
        src: templates/db.zone.j2
        dest: /etc/bind/zones/{{ zone_name }}.db

    # --- Reverse Zones ---
    - name: Deploy reverse DNS zone files
      template:
        src: templates/db.reverse.zone.j2
        dest: "/etc/bind/zones/{{ item.zone_name }}.db"
      loop: "{{ reverse_zones }}"
      loop_control:
        label: "{{ item.zone_name }}"
    
    - name: Deploy named.conf.local
      template:
        src: templates/named.conf.local.j2
        dest: /etc/bind/named.conf.local
        owner: root
        group: bind
        mode: '0644'
      notify:
        - restart bind9
        
    # --- Set Bind9 to resolve itself ---
    - name: Set local DNS to 127.0.0.1
      copy:
        dest: /etc/netplan/01-dns-local.yaml
        content: |
          network:
            version: 2
            ethernets:
              eth0:
                nameservers:
                  addresses: [127.0.0.1]

    - name: Apply netplan
      command: netplan apply
    
    - name: Restart systemd-resolved to clear old DNS
      systemd:
        name: systemd-resolved
        state: restarted

    
    
  handlers:
    - name: restart bind9
      service:
        name: bind9
        state: restarted
