- hosts: dns
  become: true
  vars_files:
    - vars/bind9_forward_vars.yml
    - vars/bind9_reverse_vars.yml
  tasks:
    - name: Install BIND9
      apt:
        name: bind9
        state: present
        update_cache: yes

    - name: Include forward zone tasks
      include_tasks: forward_zone.yml

    - name: Include reverse zone tasks
      include_tasks: reverse_zones.yml

  handlers:
    - name: restart bind9
      service:
        name: bind9
        state: restarted
