- hosts: dns
  become: true
  vars_files:
    - vars/bind9_forward_vars.yml
    - vars/bind9_reverse_vars.yml
  tasks:
    - name: Install BIND9
      apt:
        name: bind9
        state: present
        update_cache: yes

    - name: Include forward zone tasks
      include_tasks: forward_zone.yml
      vars:
        zone_name: "{{ zone_name }}"
        ttl: "{{ ttl }}"
        serial: "{{ serial }}"
        ns_records: "{{ ns_records }}"
        a_records: "{{ a_records }}"
        cname_records: "{{ cname_records }}"
        
    - name: Include reverse zone tasks
      include_tasks: reverse_zones.yml
      vars:
        reverse_zones: "{{ reverse_zones }}"
        ttl: "{{ ttl }}"
        serial: "{{ serial }}"
    
  handlers:
    - name: restart bind9
      service:
        name: bind9
        state: restarted
