- hosts: dns
  become: true
  vars_files:
    - dns/vars/bind9_vars.yml
  tasks:
    - name: Install BIND9
      apt:
        name: bind9
        state: present
        update_cache: yes

    - name: Include zone tasks
      include_tasks: dns/zones.yml

