- hosts: dns
  become: true
  vars:
    # --- Forward Zone Variables ---
    zone_name: dk-prod.lan
    ttl: 86400
    serial: 2026012801

    ns_records:
      - ns1
      - ns2

    a_records:
      - name: ca
        ip: 10.20.10.102
      - name: ntp
        ip: 10.20.10.108
      - name: ns1
        ip: 10.20.10.111
      - name: ns2
        ip: 10.20.10.112
      - name: smtp
        ip: 10.20.10.114



      
        #################################
        ### WEB Servers Proxy Reroute ###
        #################################
      - name: proxmox-node1
        ip: 10.20.10.115
      - name: proxmox-node2
        ip: 10.20.10.115
      - name: proxmox-node3
        ip: 10.20.10.115
      - name: zabbix
        ip: 10.20.10.115
      - name: ipam
        ip: 10.20.10.115
      - name: pbx
        ip: 10.20.10.115
      - name: log
        ip: 10.20.10.115
      - name: webmin
        ip: 10.20.10.115
      - name: web
        ip: 10.20.10.115
      - name: semaphore
        ip: 10.20.10.115
      - name: passbolt
        ip: 10.20.10.115




        
    cname_records: []

    # --- Reverse Zone Variables ---
    reverse_zones:
      - zone_name: "10.20.10.in-addr.arpa"
        ttl: 86400
        serial: 2026012801
        ptr_records:
          - ip_last_octet: 11
            hostname: proxmox-node1.dk-prod.lan.
          - ip_last_octet: 12
            hostname: proxmox-node2.dk-prod.lan.
          - ip_last_octet: 13
            hostname: proxmox-node3.dk-prod.lan.
          - ip_last_octet: 28
            hostname: semaphore.dk-prod.lan.
          - ip_last_octet: 101
            hostname: zabbix.dk-prod.lan.
          - ip_last_octet: 102
            hostname: ca.dk-prod.lan.
          - ip_last_octet: 103
            hostname: ipam.dk-prod.lan.
          - ip_last_octet: 108
            hostname: ntp.dk-prod.lan.
          - ip_last_octet: 109
            hostname: log.dk-prod.lan.
          - ip_last_octet: 110
            hostname: web.dk-prod.lan.
          - ip_last_octet: 111
            hostname: ns1.dk-prod.lan.
          - ip_last_octet: 112
            hostname: ns2.dk-prod.lan.
          - ip_last_octet: 113
            hostname: pbx.dk-prod.lan.
          - ip_last_octet: 114
            hostname: smtp.dk-prod.lan.
          - ip_last_octet: 115
            hostname: webmin.dk-prod.lan.
          - ip_last_octet: 116
            hostname: passbolt.dk-prod.lan.



      - zone_name: "2.20.10.in-addr.arpa"
        ttl: 86400
        serial: 2026012801
        ptr_records: []
      - zone_name: "1.20.10.in-addr.arpa"
        ttl: 86400
        serial: 2026012801
        ptr_records: []
      - zone_name: "40.20.10.in-addr.arpa"
        ttl: 86400
        serial: 2026012801
        ptr_records: []
      - zone_name: "99.20.10.in-addr.arpa"
        ttl: 86400
        serial: 2026012801
        ptr_records: []

  tasks:
    - name: Install BIND9
      apt:
        name: bind9
        state: present
        update_cache: yes

    - name: Ensure BIND zones directory exists
      file:
        path: /etc/bind/zones
        state: directory
        owner: root
        group: bind
        mode: '0755'

    - name: Deploy named.conf.options
      template:
        src: templates/named.conf.options.j2
        dest: /etc/bind/named.conf.options
        owner: root
        group: bind
        mode: '0644'
      notify:
        - restart bind9


    # --- Forward Zone ---
    - name: Deploy forward DNS zone file
      template:
        src: templates/db.zone.j2
        dest: /etc/bind/zones/{{ zone_name }}.db

    # --- Reverse Zones ---
    - name: Deploy reverse DNS zone files
      template:
        src: templates/db.reverse.zone.j2
        dest: "/etc/bind/zones/{{ item.zone_name }}.db"
      loop: "{{ reverse_zones }}"
      loop_control:
        label: "{{ item.zone_name }}"
    
    - name: Deploy named.conf.local
      template:
        src: templates/named.conf.local.j2
        dest: /etc/bind/named.conf.local
        owner: root
        group: bind
        mode: '0644'
      notify:
        - restart bind9
        
    # --- Set Bind9 to resolve itself ---
    - name: Set local DNS to 127.0.0.1
      copy:
        dest: /etc/netplan/01-dns-local.yaml
        content: |
          network:
            version: 2
            ethernets:
              eth0:
                nameservers:
                  addresses: [127.0.0.1]

    - name: Apply netplan
      command: netplan apply
       
  handlers:
    - name: restart bind9
      service:
        name: bind9
        state: restarted
