- hosts: dns
  become: true
  vars_files:
    - "{{ playbook_dir }}/vars/bind9_forward_vars.yml"
    - "{{ playbook_dir }}/vars/bind9_reverse_vars.yml"

  tasks:
    - name: Install BIND9
      apt:
        name: bind9
        state: present
        update_cache: yes

    - name: Include forward zone tasks
      include_tasks: forward_zone.yml
      vars:
        f_zone_name: "{{ zone_name }}"
        f_ns_records: "{{ ns_records }}"
        f_a_records: "{{ a_records }}"
        f_cname_records: "{{ cname_records }}"
        f_ttl: "{{ ttl }}"
        f_serial: "{{ serial }}"

        
    - name: Include reverse zone tasks
      include_tasks: reverse_zones.yml
    
  handlers:
    - name: restart bind9
      service:
        name: bind9
        state: restarted
